---
- name: Install Ingress controller
  hosts: k3s_nodes
  become: yes
  vars_files:
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/{{ env }}.yml
  roles:
    - ../roles/ingress_controller
...