---
- name: Copy K3s Kubeconfig to user home
  hosts: k3s_nodes
  vars_files:
    - ../inventory/group_vars/all.yml
  tasks:
    - name: Fetch config from remote
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes
      when: not ansible_check_mode
...
